import { useCallback, useState } from 'react';
import type { PlanId } from '@/constants';
import { AuthCard, AuthLayout, FormError, OAuthButtons, OrDivider, PasswordField, PasswordStrength, PlanPicker, SubmitButton, TextField } from '../components';
import { AUTH_COPY, AUTH_ROUTES } from '../constants';
import { useDocumentTitle } from '../hooks/useDocumentTitle';
import { useSignup } from '../hooks/useSignup';

interface SignupPageProps { navigate: (path: string) => void; }
const initialPlan = (): PlanId => { const plan = new URLSearchParams(window.location.search).get('plan'); return plan === 'pro' || plan === 'pro-plus' ? plan : 'free'; };
export const SignupPage: React.FC<SignupPageProps> = ({ navigate }) => { useDocumentTitle('Create account — TermHive'); const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [plan, setPlan] = useState<PlanId>(initialPlan); const { pending, error, fields, submit } = useSignup(); const onSubmit = useCallback((event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); void submit(name, email, password, plan, navigate); }, [email, name, navigate, password, plan, submit]); return <AuthLayout><AuthCard body={AUTH_COPY.signup.body} title={AUTH_COPY.signup.title}><PlanPicker onChange={setPlan} plan={plan} /><OAuthButtons mode="signup" plan={plan} /><OrDivider /><form onSubmit={onSubmit}><TextField autoComplete="name" error={fields.name} label="Name" onChange={(event) => setName(event.target.value)} value={name} /><TextField autoComplete="email" error={fields.email} label="Email" onChange={(event) => setEmail(event.target.value)} type="email" value={email} /><PasswordField autoComplete="new-password" error={fields.password} onChange={(event) => setPassword(event.target.value)} value={password} /><PasswordStrength email={email} password={password} />{error ? <FormError>{error}</FormError> : null}<SubmitButton pending={pending}>Create account</SubmitButton></form><p className="auth-legal">{AUTH_COPY.legal}</p><p className="auth-footer">Already have an account? <a href={AUTH_ROUTES.LOGIN}>Sign in</a></p></AuthCard></AuthLayout>; };
