// Writes the workspace GraphQL schema (SDL) for client codegen.
// Usage: npm run graphql:schema
import { build } from 'esbuild';
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const out = path.join(root, 'client/src/lib/graphql/schema.graphql');
const tmp = mkdtempSync(path.join(root, 'dist', '.schema-'));

try {
  const entry = path.join(tmp, 'schema.mjs');
  await build({
    entryPoints: [path.join(root, 'src/graphql/schema.ts')],
    bundle: true,
    platform: 'node',
    format: 'esm',
    packages: 'external',
    outfile: entry,
    logLevel: 'error',
  });
  const { schema } = await import(pathToFileURL(entry).href);
  const { printSchema } = await import('graphql');
  writeFileSync(
    out,
    `# Generated by npm run graphql:schema — do not edit.\n${printSchema(schema)}\n`,
  );
  console.log(`wrote ${path.relative(root, out)}`);
} finally {
  rmSync(tmp, { recursive: true, force: true });
}
